GET http://localhost:8080

###

POST http://localhost:8080/users/register

###
POST http://localhost:8080/users/refresh-token

###
POST http://localhost:8080/users/login

###
POST http://localhost:8080/users/logout