GET http://localhost:8080

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
    "email": "Tnam5522@gmail.com",
    "password": "12345678"
}
###
POST http://localhost:8080/users/refresh-token

###
POST http://localhost:8080/users/login

###
POST http://localhost:8080/users/logout